## Introduction to Pytorch Tensors

### Creating Tensors

In [3]:
import torch
import math

In [4]:
# 텐서 생성
x = torch.empty(3, 4) # 2차원 텐서 = 행렬
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
zeros = torch.zeros(2, 3) # 0으로 채워진 텐서
print(zeros)

ones = torch.ones(2, 3) # 1로 채워진 텐서
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3) # 0~1 사이의 랜덤값으로 채워진 텐서
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


### Random Tensors and Seeding

In [6]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### Tensor Shapes

동일한 차원과 각 차원의 셀 수가 동일해야하는 경우 >> torch.*_like() 사용

In [7]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [8]:
# 직접 데이터 지정하여 텐서 제작
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


### Tensor Data Types

In [9]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


사용 가능한 데이터 유형은 아래와 같음

* torch.bool

* torch.int8

* torch.uint8

* torch.int16

* torch.int32

* torch.int64

* torch.half

* torch.float

* torch.double

* torch.bfloat

### Math & Logic with PyTorch Tensors

In [10]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])
tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [11]:
# 아래 셀은 오류를 발생시킨다. >> 오류 확인!
# 모양이 다른 경우 텐서에서 이진 연산을 수행하려고 하니 에러가 나는 것을 볼 수 있음

a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

### In Brief: Tensor Broadcasting

텐서 브로드캐스팅

> 모양이 유사한 텐서 간에 작업을 수행하는 방법

> 딥러닝에서는 일반적으로 학습 가중치 텐서에 입력 텐서 배치를 곱하고 배치의 각 인스턴스에 개별적으로 작업 적용하고 동일한 모양의 텐서를 반환하는 것임

> (ex) (2,4) * (1,4) = (2,4)

In [12]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


In [13]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]],

        [[0.2138, 0.5395],
         [0.3686, 0.4007],
         [0.7220, 0.8217]]])
tensor([[[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]],

        [[0.2612, 0.2612],
         [0.7375, 0.7375],
         [0.8328, 0.8328]]])
tensor([[[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]],

        [[0.8444, 0.2941],
         [0.8444, 0.2941],
         [0.8444, 0.2941]]])


In [14]:
# 아래 셀은 런타임 오류를 발생시킨다. >> 오류 확인!

a =     torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # dimensions must match last-to-first : 차원은 처음과 마지막이 일치해야함

c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different : 차원 수가 다름

d = a * torch.rand((0, ))   # can't broadcast with an empty tensor : 텐서가 비어 있음

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

### More Math with Tensors

In [20]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a)) # 절대값
print(torch.ceil(a)) # 올림
print(torch.floor(a)) # 내림
print(torch.clamp(a, -0.5, 0.5)) # min 혹은 max의 범주에 해당하지 않는 값들 범주에 맞게 변경

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines) # 역삼각함수 : 아크사인
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print('cross : \n', torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print('torch.rand(2, 2) : \n', m1)
m3 = torch.matmul(m1, m2)
print('matmul : \n', m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.4695, 0.4657, 0.5747, 0.1185],
        [0.2246, 0.2155, 0.5310, 0.4235]])
tensor([[-0., 1., -0., -0.],
        [-0., 1., -0., 1.]])
tensor([[-1.,  0., -1., -1.],
        [-1.,  0., -1.,  0.]])
tensor([[-0.4695,  0.4657, -0.5000, -0.1185],
        [-0.2246,  0.2155, -0.5000,  0.4235]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
cross : 
 tensor([ 0.,  0., -1.])
torch.rand(2, 2) : 
 tensor([[0.7402, 0.4467],
        [0.8499, 0.1399]])
matmul : 
 tensor([[2.2206, 1.3401],
        [2.5496, 0.4198]])
torch.return_types.svd(
U=tensor([[-0.7085, -0.7057],
        [-0.7057,  0.7085]]),
S=tensor([3.5953, 0.6910]),
V=tensor([[-0.9381,  

### Altering Tensors in Place

함수 뒤에 _(언더바)를 붙여주면,

inplace=True와 같은 역할

In [53]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [54]:
# 산술 연산의 경우도 마찬가지 작동

a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9197, 0.9399],
        [0.7340, 0.7090]])

After adding:
tensor([[1.9197, 1.9399],
        [1.7340, 1.7090]])
tensor([[1.9197, 1.9399],
        [1.7340, 1.7090]])
tensor([[0.9197, 0.9399],
        [0.7340, 0.7090]])

After multiplying
tensor([[0.8459, 0.8833],
        [0.5388, 0.5027]])
tensor([[0.8459, 0.8833],
        [0.5388, 0.5027]])


In [76]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c) # out 출력을 수신할 텐서를 지정
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values : c와 d는 동일한 값을 포함하는 것이 아닌 동일한 개체임
assert id(c), old_id    # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c), old_id    # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[1.1540, 0.9881],
        [1.2381, 1.0946]])
tensor([[0.8115, 0.8870],
        [0.5763, 0.6694]])


### Copying Tensors

In [55]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered : 동일하게 변경됨

tensor([[  1., 561.],
        [  1.,   1.]])


In [56]:
a = torch.ones(2, 2)
b = a.clone() # clone : 별도의 복사본 만들기

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [57]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone() # detach로 가중치 추적 없이 계산 수행
print(c)

print(a)

tensor([[0.8198, 0.2172],
        [0.1861, 0.7556]], requires_grad=True)
tensor([[0.8198, 0.2172],
        [0.1861, 0.7556]], grad_fn=<CloneBackward0>)
tensor([[0.8198, 0.2172],
        [0.1861, 0.7556]])
tensor([[0.8198, 0.2172],
        [0.1861, 0.7556]], requires_grad=True)


### Moving to GPU

CUDA 호환 GPU 및 CUDA 드라이버가 설치되어 있지 않은 경우 이 섹션의 실행 셀은 GPU 관련 코드를 실행하지 않음

In [58]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [60]:
# 데이터를 장치로 가져오기
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


In [61]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.5841, 0.9205],
        [0.3687, 0.3966]])


In [62]:
y = torch.rand(2, 2)
y = y.to(my_device) # to : 다른 쪽으로 텐서 이동

In [63]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='gpu')
z = x + y  # exception will be thrown : 텐서 연산 수행시 모든 텐서가 동일한 장치에 있어야 함

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, privateuseone device type at start of device string: gpu

### Manipulating Tensor Shapes

#### Changing the Number of Dimensions

차원 수 변경

In [64]:
a = torch.rand(3, 226, 226) # 3 채널, 226*226 사이즈
b = a.unsqueeze(0) # 0번째 차원 추가

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [65]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.8578]]]]])


In [22]:
# 차원 비교
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0) # 차원 줄이기
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)
print(c)

d = c.squeeze(0)
print(d.shape)
print(d)

torch.Size([1, 20])
tensor([[0.9280, 0.1986, 0.1779, 0.6366, 0.2301, 0.9151, 0.5056, 0.2659, 0.5251,
         0.1631, 0.7391, 0.9254, 0.2546, 0.9369, 0.7488, 0.9106, 0.8941, 0.7992,
         0.0554, 0.5776]])
torch.Size([20])
tensor([0.9280, 0.1986, 0.1779, 0.6366, 0.2301, 0.9151, 0.5056, 0.2659, 0.5251,
        0.1631, 0.7391, 0.9254, 0.2546, 0.9369, 0.7488, 0.9106, 0.8941, 0.7992,
        0.0554, 0.5776])
torch.Size([2, 2])
tensor([[0.9130, 0.9833],
        [0.7706, 0.2174]])
torch.Size([2, 2])
tensor([[0.9130, 0.9833],
        [0.7706, 0.2174]])


In [23]:
a = torch.ones(4, 3, 2)
print(a)

c = a * torch.rand(3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[[0.2038, 0.2038],
         [0.2881, 0.2881],
         [0.2677, 0.2677]],

        [[0.2038, 0.2038],
         [0.2881, 0.2881],
         [0.2677, 0.2677]],

        [[0.2038, 0.2038],
         [0.2881, 0.2881],
         [0.2677, 0.2677]],

        [[0.2038, 0.2038],
         [0.2881, 0.2881],
         [0.2677, 0.2677]]])


In [32]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end : 차원 추가
print(a.shape)
print(b.shape)
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([4, 3, 2])
torch.Size([3])
torch.Size([3, 1])
tensor([[[0.3069, 0.3069],
         [0.3758, 0.3758],
         [0.9553, 0.9553]],

        [[0.3069, 0.3069],
         [0.3758, 0.3758],
         [0.9553, 0.9553]],

        [[0.3069, 0.3069],
         [0.3758, 0.3758],
         [0.9553, 0.9553]],

        [[0.3069, 0.3069],
         [0.3758, 0.3758],
         [0.9553, 0.9553]]])


In [37]:
batch_me = torch.rand(3, 226, 226)
print(batch_me)
print(batch_me.shape)
batch_me.unsqueeze_(0) # 인플레이스 적용(_)해서 차원 추가
print(batch_me)
print(batch_me.shape)

tensor([[[0.2530, 0.8060, 0.9073,  ..., 0.2750, 0.0533, 0.3208],
         [0.2347, 0.0550, 0.9968,  ..., 0.6488, 0.2107, 0.7595],
         [0.2201, 0.9034, 0.0433,  ..., 0.7371, 0.9103, 0.2124],
         ...,
         [0.6790, 0.7808, 0.5495,  ..., 0.6651, 0.8474, 0.6027],
         [0.9298, 0.8795, 0.5788,  ..., 0.1338, 0.2261, 0.2232],
         [0.4417, 0.5264, 0.8071,  ..., 0.4836, 0.4403, 0.1981]],

        [[0.4266, 0.7244, 0.6898,  ..., 0.1335, 0.5360, 0.6872],
         [0.4110, 0.9128, 0.6693,  ..., 0.7138, 0.3637, 0.7326],
         [0.7472, 0.5488, 0.0175,  ..., 0.3780, 0.6648, 0.4464],
         ...,
         [0.8521, 0.1304, 0.0485,  ..., 0.5005, 0.7146, 0.5307],
         [0.8109, 0.2255, 0.3124,  ..., 0.0348, 0.4512, 0.9984],
         [0.7868, 0.7706, 0.3193,  ..., 0.3753, 0.4500, 0.9484]],

        [[0.4624, 0.4758, 0.8566,  ..., 0.2929, 0.5341, 0.0478],
         [0.3170, 0.8296, 0.2881,  ..., 0.7350, 0.6591, 0.5247],
         [0.5770, 0.4575, 0.2104,  ..., 0.2835, 0.0118, 0.

In [38]:
# Convolution kernel은 채널*너비*높이 형태의 출력텐서를 생성하지만,
# 선형 레이어는 1차원 입력해야하므로 shape 변경해주는 reshape 수행
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


### NumPy Bridge

"numpy의 ndarray"와 "torch의 tensor" 간의 전환

In [41]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array) # ndarray를 tensor로 바꾸기
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [42]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy() # tensor를 ndarray로 바꾸기
print(numpy_rand)

tensor([[0.1684, 0.8832, 0.1781],
        [0.7375, 0.2606, 0.2977]])
[[0.16839826 0.88322884 0.17813545]
 [0.73746306 0.26055974 0.29770023]]


In [45]:
# 이렇게 변환된 객체가 소스 객체와 동일한 메모리를 사용한다는 것을 확인
numpy_array[1, 1] = 23
print(numpy_array) # 같이 바뀜
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(pytorch_rand) # 같이 바뀜
print(numpy_rand)

[[ 1.  1.  1.]
 [ 1. 23.  1.]]
tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
tensor([[ 0.1684,  0.8832,  0.1781],
        [ 0.7375, 17.0000,  0.2977]])
[[ 0.16839826  0.88322884  0.17813545]
 [ 0.73746306 17.          0.29770023]]
